FAREWELLS = [
    "Bye, don't be shy—come back and say hi! 👋",
    "See you later, alligator! After a while, crocodile! 🐊",
    "Time to fly, goodbye! ✈️",
    "Out the door, but we'll chat some more! 🚪",
    "Take care, be a millionaire! 💰",
    "Catch you soon, under the moon! 🌙",
    "Don't be a stranger, office ranger! 🤠",
    "Peace out, no doubt! ✌️",
    "Have some fun in the sun! ☀️",
    "Farewell, and do well! 🌟",
    "Keep in touch, you'll be missed so much! 💌",
    "Don't delay, have a great day! 😊",
    "So long, stay strong! 💪",
    "You're off the clock, don't forget to rock! 🎸",
    "Bye for now, take a bow! 🎭",
    "Bye-bye, butterfly! 🦋",
    "See ya, wouldn't wanna be ya! 😜",
    "See you soon, raccoon! 🦝",
    "Take care, polar bear! 🐻‍❄️",
    "Later, tater! 🥔",
    "Peace out, Brussels sprout! 🥬",
    "Catch you later, investigator! 🕵️",
    "Have a good one, pudding! 🍮",
    "Cheerio, amigo! 🤝",
    "See ya, tortilla! 🌮",
    "Bye, french fry! 🍟",
    "Have a blast, see you fast! 💥",
    "Toodle-oo, kangaroo! 🦘",
    "Take it easy, cheesy! 🧀",
    "Keep it real, banana peel! 🍌",
    "Stay cool, poodle! 🐩",
    "Until next time, lime! 🍋",
    "Off you pop, lollipop! 🍭",
    "Don't work too hard, superstar! ⭐",
    "Be good, neighborhood! 🏘️",
    "Have a great night, don't let the bugs bite! 😴",
    "Smell ya later, alligator! 🐊",
    "Have fun, cinnamon bun! 🧁",
    "See you around, hound! 🐶",
    "See you tomorrow, avocado! 🥑",
    "May your meetings be short and your coffee be strong! ☕",
    "May your inbox stay empty! 📧",
    "May the traffic be ever in your favor! 🚗",
    "Clock out and chill out! ❄️",
    "Log off and lift off! 🚀",
    "Go home and roam! 🏡",
    "Spreadsheet complete, now retreat! 📊",
    "Work is done, go have fun! 🎉",
]
