DAD_JOKES = [
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "I told my boss three companies were after me, so he gave me a raise. The other three were the electric, water, and gas company.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "I'm reading a book about anti-gravity. It's impossible to put down.",
    "Why did the scarecrow win an award? He was outstanding in his field.",
    "I used to be a banker, but I lost interest.",
    "Why do clocks always go clockwise? Have you ever seen one going otherwise?",
    "Time flies like an arrow. Fruit flies like a banana.",
    "I'm on a seafood diet. I see food and I eat it.",
    "Why did the coffee file a police report? It got mugged.",
    "How does a penguin build its house? Igloos it together.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "What do you call a fish with no eyes? A fsh.",
    "I used to hate facial hair, but then it grew on me.",
    "Why can't your nose be 12 inches long? Because then it would be a foot.",
    "What do you call a factory that makes okay products? A satisfactory.",
    "I'm terrified of elevators, so I'm going to start taking steps to avoid them.",
    "Why did the employee get excited about their retirement plan? It had a lot of 401k appeal.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
]
